
tasks:
  build-deps:
    runner: razorci/openjdk:11-buster
    steps:
    - checkout
    - commands:
      - |
        
        mvn clean package sonar:sonar \
          -Dsonar.projectKey=sample \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=9405ec0bcd254200164171c5596e98965b382562
          
