
tasks:
  build-deps:
    runner: razorci/openjdk:11-buster
    steps:
    - checkout
    - commands:
      - |
        
        mvn clean install sonar:sonar \
          -Dsonar.projectKey=java-app \
          -Dsonar.host.url= http://f577-115-241-195-210.in.ngrok.io  \
          -Dsonar.login=4c3863b5ce20639abc99505f2fb52f9fa656d174
          
