tasks:
  unit-test:
    runner: razorci/openjdk:11-buster
    steps:
    - checkout
    - commands:
      - |
        mvn clean package
        ls -a 
        ls target
        docker build -t application .
    - docker/push:
        image: apllication
        tags: [app1]


