tasks:
  unit-test:
    runner: razorci/openjdk:11-buster
    steps:
    - checkout
    - commands:
      - |
        mvn clean package
        ls -a 
        cp -r valaxy-2.0-RELEASE.war ec2-user@13.233.216.150:/opt/apache-tomcat-8.5.81/webapps

