tasks:
  unit-test:
    runner: razorci/openjdk:11-buster
    steps:
    - checkout
    - commands:
      - |
        mvn clean package
        ls -a 
        ls target
        #scp -r target/valaxy-2.0-RELEASE.war ubuntu@13.235.13.95:/opt/apache-tomcat-8.5.81/webapps
        docker build -t application .
        
    # - docker/build:
    #     image: dockergub/webapp:v1
     #    tags: [v1]
      #   dockerfile: Dockerfile.build
      
      - docker/push:
          image: dockerhub.com/webapp
          tags: [app1]


