tasks:
  unit-test:
    runner: razorci/openjdk:11-buster
    steps:
    - checkout
    - commands:
      - |
        mvn clean package
        ls -a 
        scp -r target/valaxy-2.0-RELEASE.war ubuntu@13.233.216.150:/opt/apache-tomcat-8.5.81/webapps

